display_name="The WuBoy Ultimate Modpack"
description="""
Compiled by WuBoy

A wi-fi safe modpack. Currently very unfinished. You can see a list of all of the mods here: https://tinyurl.com/WuBoyModpack
"""
version="11.0.1-3/30/2021"
category="Misc"