[bgm_z34_f_ike]
costume_0 = 0
costume_1 = 1
costume_2 = 0
costume_3 = 1
costume_4 = 0
costume_5 = 1
costume_6 = 0
costume_7 = 1

[bgm_zz01_f_dolly]
costume_0 = 0
costume_1 = 0
costume_2 = 0
costume_3 = 0
costume_4 = 1
costume_5 = 2
costume_6 = 0
costume_7 = 0